AWSTemplateFormatVersion: 2010-09-09
Outputs:
  ApiGatewayId:
    Value:
      Fn::Sub: ${ServerlessHttpApi}
  ApiGatewayUrl:
    Value:
      Fn::Sub: https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/
  LambdaArn:
    Value:
      Fn::GetAtt:
      - ServerFunction
      - Arn
Resources:
  ServerFunction:
    Properties:
      AutoPublishAlias: live
      Environment:
        Variables:
          GUNICORN_CMD_ARGS: --bind=0.0.0.0
          PYTHONUNBUFFERED: "1"
          UVICORN_HOST: 0.0.0.0
          ZEET_APP: my-ccvi-project-major
          ZEET_DEPLOYMENT_ID: d87c3602-3fa5-44cb-a2bf-dc505978b472
          ZEET_ENVIRONMENT: Demo
          ZEET_PROJECT: CCVI
          ZEET_SERVERLESS_ENTRYPOINT: python3 main.py
          ZEET_SERVERLESS_PORT: "5000"
      Events:
        CatchAll:
          Properties:
            Method: ANY
            Path: /{proxy+}
          Type: HttpApi
      ImageUri: 649177576069.dkr.ecr.us-west-2.amazonaws.com/zeet/lambda:53004e3c-0e7b-48b6-8cf6-5eb75610729e-d87c3602-3fa5-44cb-a2bf-dc505978b472
      MemorySize: 1000
      PackageType: Image
      Timeout: 180
      VersionDescription: d87c3602-3fa5-44cb-a2bf-dc505978b472
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
