ServerFunction:
    Properties:
      AutoPublishAlias: live
      Environment:
        Variables:
          # other environment variables
      Events:
        CatchAll:
          Properties:
            Method: ANY
            Path: /{proxy+}
          Type: HttpApi
      ImageUri: 649177576069.dkr.ecr.us-west-2.amazonaws.com/zeet/lambda:53004e3c-0e7b-48b6-8cf6-5eb75610729e-0a8eb56f-e050-4789-ac79-893eb661a51d
      MemorySize: 1000
      PackageType: Image
      Timeout: 120 # increase timeout to 120 seconds
      VersionDescription: 0a8eb56f-e050-4789-ac79-893eb661a51d
    Type: AWS::Serverless::Function
